package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Artikl implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "artikl id")
   private java.lang.Integer artiklId;
   @org.kie.api.definition.type.Label(value = "naziv artikla")
   private java.lang.String nazivArtikla;
   @org.kie.api.definition.type.Label(value = "cijena artikla")
   private java.lang.String cijenaArtikla;

   public Artikl()
   {
   }

   public java.lang.Integer getArtiklId()
   {
      return this.artiklId;
   }

   public void setArtiklId(java.lang.Integer artiklId)
   {
      this.artiklId = artiklId;
   }

   public java.lang.String getNazivArtikla()
   {
      return this.nazivArtikla;
   }

   public void setNazivArtikla(java.lang.String nazivArtikla)
   {
      this.nazivArtikla = nazivArtikla;
   }

   public java.lang.String getCijenaArtikla()
   {
      return this.cijenaArtikla;
   }

   public void setCijenaArtikla(java.lang.String cijenaArtikla)
   {
      this.cijenaArtikla = cijenaArtikla;
   }

   public Artikl(java.lang.Integer artiklId, java.lang.String nazivArtikla,
         java.lang.String cijenaArtikla)
   {
      this.artiklId = artiklId;
      this.nazivArtikla = nazivArtikla;
      this.cijenaArtikla = cijenaArtikla;
   }

}