package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dokumentacija implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "dokumentacija id")
   private java.lang.Integer dokumentacijaId;
   @org.kie.api.definition.type.Label(value = "naziv dokumentacije")
   private java.lang.String nazivDokumentacije;
   @org.kie.api.definition.type.Label(value = "kompletna dokumentacija")
   private java.lang.Boolean kompletnaDokumentacija;

   public Dokumentacija()
   {
   }

   public java.lang.Integer getDokumentacijaId()
   {
      return this.dokumentacijaId;
   }

   public void setDokumentacijaId(java.lang.Integer dokumentacijaId)
   {
      this.dokumentacijaId = dokumentacijaId;
   }

   public java.lang.String getNazivDokumentacije()
   {
      return this.nazivDokumentacije;
   }

   public void setNazivDokumentacije(java.lang.String nazivDokumentacije)
   {
      this.nazivDokumentacije = nazivDokumentacije;
   }

   public java.lang.Boolean getKompletnaDokumentacija()
   {
      return this.kompletnaDokumentacija;
   }

   public void setKompletnaDokumentacija(
         java.lang.Boolean kompletnaDokumentacija)
   {
      this.kompletnaDokumentacija = kompletnaDokumentacija;
   }

   public Dokumentacija(java.lang.Integer dokumentacijaId,
         java.lang.String nazivDokumentacije,
         java.lang.Boolean kompletnaDokumentacija)
   {
      this.dokumentacijaId = dokumentacijaId;
      this.nazivDokumentacije = nazivDokumentacije;
      this.kompletnaDokumentacija = kompletnaDokumentacija;
   }

}