package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dokumentacija implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Polozajni_nacrt")
   private boolean polozajniNacrt;
   @org.kie.api.definition.type.Label(value = "Gradjevinska_dozvola")
   private boolean gradjevinskaDozvola;
   @org.kie.api.definition.type.Label(value = "Gruntovni_izvadak")
   private boolean gruntovniIzvadak;

   public Dokumentacija()
   {
   }

   public boolean isPolozajniNacrt()
   {
      return this.polozajniNacrt;
   }

   public void setPolozajniNacrt(boolean polozajniNacrt)
   {
      this.polozajniNacrt = polozajniNacrt;
   }

   public boolean isGradjevinskaDozvola()
   {
      return this.gradjevinskaDozvola;
   }

   public void setGradjevinskaDozvola(boolean gradjevinskaDozvola)
   {
      this.gradjevinskaDozvola = gradjevinskaDozvola;
   }

   public boolean isGruntovniIzvadak()
   {
      return this.gruntovniIzvadak;
   }

   public void setGruntovniIzvadak(boolean gruntovniIzvadak)
   {
      this.gruntovniIzvadak = gruntovniIzvadak;
   }

   public Dokumentacija(boolean polozajniNacrt, boolean gradjevinskaDozvola,
         boolean gruntovniIzvadak)
   {
      this.polozajniNacrt = polozajniNacrt;
      this.gradjevinskaDozvola = gradjevinskaDozvola;
      this.gruntovniIzvadak = gruntovniIzvadak;
   }

}