package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DozvolaPrijekopa implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "dozvola prijekopa id")
   private java.lang.Integer dozvolaPrijekopaId;
   @org.kie.api.definition.type.Label(value = "datum izdavanja dozvole")
   private java.util.Date datumIzdavanja;

   public DozvolaPrijekopa()
   {
   }

   public java.lang.Integer getDozvolaPrijekopaId()
   {
      return this.dozvolaPrijekopaId;
   }

   public void setDozvolaPrijekopaId(java.lang.Integer dozvolaPrijekopaId)
   {
      this.dozvolaPrijekopaId = dozvolaPrijekopaId;
   }

   public java.util.Date getDatumIzdavanja()
   {
      return this.datumIzdavanja;
   }

   public void setDatumIzdavanja(java.util.Date datumIzdavanja)
   {
      this.datumIzdavanja = datumIzdavanja;
   }

   public DozvolaPrijekopa(java.lang.Integer dozvolaPrijekopaId,
         java.util.Date datumIzdavanja)
   {
      this.dozvolaPrijekopaId = dozvolaPrijekopaId;
      this.datumIzdavanja = datumIzdavanja;
   }

}