package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DozvolaPrijekopa implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "dozvolaPrijekopa_Id")
   private java.lang.String dozvolaPrijekopaId;
   @org.kie.api.definition.type.Label(value = "datum_izdavanja")
   private java.util.Date datumIzdavanjaDozvole;
   @org.kie.api.definition.type.Label(value = "datum_do")
   private java.util.Date datumVazenjaDozvole;

   public DozvolaPrijekopa()
   {
   }

   public java.lang.String getDozvolaPrijekopaId()
   {
      return this.dozvolaPrijekopaId;
   }

   public void setDozvolaPrijekopaId(java.lang.String dozvolaPrijekopaId)
   {
      this.dozvolaPrijekopaId = dozvolaPrijekopaId;
   }

   public java.util.Date getDatumIzdavanjaDozvole()
   {
      return this.datumIzdavanjaDozvole;
   }

   public void setDatumIzdavanjaDozvole(java.util.Date datumIzdavanjaDozvole)
   {
      this.datumIzdavanjaDozvole = datumIzdavanjaDozvole;
   }

   public java.util.Date getDatumVazenjaDozvole()
   {
      return this.datumVazenjaDozvole;
   }

   public void setDatumVazenjaDozvole(java.util.Date datumVazenjaDozvole)
   {
      this.datumVazenjaDozvole = datumVazenjaDozvole;
   }

   public DozvolaPrijekopa(java.lang.String dozvolaPrijekopaId,
         java.util.Date datumIzdavanjaDozvole,
         java.util.Date datumVazenjaDozvole)
   {
      this.dozvolaPrijekopaId = dozvolaPrijekopaId;
      this.datumIzdavanjaDozvole = datumIzdavanjaDozvole;
      this.datumVazenjaDozvole = datumVazenjaDozvole;
   }

}