package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IzmjeraPrikljucka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "izmjera prikljucka")
   private java.lang.Integer izmjeraPrikljuckaId;
   @org.kie.api.definition.type.Label(value = "duzina prikljucka")
   private java.lang.String duzinaPrikljucka;
   @org.kie.api.definition.type.Label(value = "duzina prikljucka")
   private java.lang.String dubinaPrikljucka;
   @org.kie.api.definition.type.Label(value = "profil prikljucka")
   private java.lang.String profilPrikljucka;

   public IzmjeraPrikljucka()
   {
   }

   public java.lang.Integer getIzmjeraPrikljuckaId()
   {
      return this.izmjeraPrikljuckaId;
   }

   public void setIzmjeraPrikljuckaId(java.lang.Integer izmjeraPrikljuckaId)
   {
      this.izmjeraPrikljuckaId = izmjeraPrikljuckaId;
   }

   public java.lang.String getDuzinaPrikljucka()
   {
      return this.duzinaPrikljucka;
   }

   public void setDuzinaPrikljucka(java.lang.String duzinaPrikljucka)
   {
      this.duzinaPrikljucka = duzinaPrikljucka;
   }

   public java.lang.String getDubinaPrikljucka()
   {
      return this.dubinaPrikljucka;
   }

   public void setDubinaPrikljucka(java.lang.String dubinaPrikljucka)
   {
      this.dubinaPrikljucka = dubinaPrikljucka;
   }

   public java.lang.String getProfilPrikljucka()
   {
      return this.profilPrikljucka;
   }

   public void setProfilPrikljucka(java.lang.String profilPrikljucka)
   {
      this.profilPrikljucka = profilPrikljucka;
   }

   public IzmjeraPrikljucka(java.lang.Integer izmjeraPrikljuckaId,
         java.lang.String duzinaPrikljucka,
         java.lang.String dubinaPrikljucka, java.lang.String profilPrikljucka)
   {
      this.izmjeraPrikljuckaId = izmjeraPrikljuckaId;
      this.duzinaPrikljucka = duzinaPrikljucka;
      this.dubinaPrikljucka = dubinaPrikljucka;
      this.profilPrikljucka = profilPrikljucka;
   }

}