package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IzvedbaPrikljucka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "izvedba id")
   private java.lang.Integer izvedbaId;
   @org.kie.api.definition.type.Label(value = "datum izvedbe")
   private java.util.Date datumIzvedbe;
   @org.kie.api.definition.type.Label(value = "nalog")
   private bpm_vvg_2015.procesiugovaranjaprikljucaka.NalogIzvedba nalog;
   @org.kie.api.definition.type.Label(value = "dozvola prijekopa")
   private java.lang.Boolean dozvolaPrijekopa;

   public IzvedbaPrikljucka()
   {
   }

   public java.lang.Integer getIzvedbaId()
   {
      return this.izvedbaId;
   }

   public void setIzvedbaId(java.lang.Integer izvedbaId)
   {
      this.izvedbaId = izvedbaId;
   }

   public java.util.Date getDatumIzvedbe()
   {
      return this.datumIzvedbe;
   }

   public void setDatumIzvedbe(java.util.Date datumIzvedbe)
   {
      this.datumIzvedbe = datumIzvedbe;
   }

   public bpm_vvg_2015.procesiugovaranjaprikljucaka.NalogIzvedba getNalog()
   {
      return this.nalog;
   }

   public void setNalog(
         bpm_vvg_2015.procesiugovaranjaprikljucaka.NalogIzvedba nalog)
   {
      this.nalog = nalog;
   }

   public java.lang.Boolean getDozvolaPrijekopa()
   {
      return this.dozvolaPrijekopa;
   }

   public void setDozvolaPrijekopa(java.lang.Boolean dozvolaPrijekopa)
   {
      this.dozvolaPrijekopa = dozvolaPrijekopa;
   }

   public IzvedbaPrikljucka(java.lang.Integer izvedbaId,
         java.util.Date datumIzvedbe,
         bpm_vvg_2015.procesiugovaranjaprikljucaka.NalogIzvedba nalog,
         java.lang.Boolean dozvolaPrijekopa)
   {
      this.izvedbaId = izvedbaId;
      this.datumIzvedbe = datumIzvedbe;
      this.nalog = nalog;
      this.dozvolaPrijekopa = dozvolaPrijekopa;
   }

}