package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Korisnik implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Korisnik_Id")
   private java.lang.String korisnikId;
   @org.kie.api.definition.type.Label(value = "Ime_korisnika")
   private java.lang.String imeKorisnika;
   @org.kie.api.definition.type.Label(value = "Prezime_korisnika")
   private java.lang.String prezimeKorisnika;
   @org.kie.api.definition.type.Label(value = "Oib_korisnika")
   private java.lang.String obiKorisnika;
   @org.kie.api.definition.type.Label(value = "Adresa_korisnika")
   private java.lang.String adresaKorisnika;
   @org.kie.api.definition.type.Label(value = "Broj_telefona_korisnika")
   private java.lang.String brojTelefonaKorisnika;

   public Korisnik()
   {
   }

   public java.lang.String getKorisnikId()
   {
      return this.korisnikId;
   }

   public void setKorisnikId(java.lang.String korisnikId)
   {
      this.korisnikId = korisnikId;
   }

   public java.lang.String getImeKorisnika()
   {
      return this.imeKorisnika;
   }

   public void setImeKorisnika(java.lang.String imeKorisnika)
   {
      this.imeKorisnika = imeKorisnika;
   }

   public java.lang.String getPrezimeKorisnika()
   {
      return this.prezimeKorisnika;
   }

   public void setPrezimeKorisnika(java.lang.String prezimeKorisnika)
   {
      this.prezimeKorisnika = prezimeKorisnika;
   }

   public java.lang.String getObiKorisnika()
   {
      return this.obiKorisnika;
   }

   public void setObiKorisnika(java.lang.String obiKorisnika)
   {
      this.obiKorisnika = obiKorisnika;
   }

   public java.lang.String getAdresaKorisnika()
   {
      return this.adresaKorisnika;
   }

   public void setAdresaKorisnika(java.lang.String adresaKorisnika)
   {
      this.adresaKorisnika = adresaKorisnika;
   }

   public java.lang.String getBrojTelefonaKorisnika()
   {
      return this.brojTelefonaKorisnika;
   }

   public void setBrojTelefonaKorisnika(java.lang.String brojTelefonaKorisnika)
   {
      this.brojTelefonaKorisnika = brojTelefonaKorisnika;
   }

   public Korisnik(java.lang.String korisnikId, java.lang.String imeKorisnika,
         java.lang.String prezimeKorisnika, java.lang.String obiKorisnika,
         java.lang.String adresaKorisnika,
         java.lang.String brojTelefonaKorisnika)
   {
      this.korisnikId = korisnikId;
      this.imeKorisnika = imeKorisnika;
      this.prezimeKorisnika = prezimeKorisnika;
      this.obiKorisnika = obiKorisnika;
      this.adresaKorisnika = adresaKorisnika;
      this.brojTelefonaKorisnika = brojTelefonaKorisnika;
   }

}