package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Korisnik implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Korisnik() {
    }

}