package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Korisnik implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "korisnik id")
   private java.lang.Integer korisnikId;
   @org.kie.api.definition.type.Label(value = "imeKorisnika")
   private java.lang.String imeKorisnika;
   @org.kie.api.definition.type.Label(value = "prezime korisnika")
   private java.lang.String prezimeKorisnika;
   @org.kie.api.definition.type.Label(value = "adresa korisnika")
   private java.lang.String adresaKorisnika;
   @org.kie.api.definition.type.Label(value = "broj telefona korisnika")
   private java.lang.String brojTelefonaKorisnika;
   @org.kie.api.definition.type.Label(value = "oib korisnika")
   private java.lang.String oibKorisnika;

   public Korisnik()
   {
   }

   public java.lang.Integer getKorisnikId()
   {
      return this.korisnikId;
   }

   public void setKorisnikId(java.lang.Integer korisnikId)
   {
      this.korisnikId = korisnikId;
   }

   public java.lang.String getImeKorisnika()
   {
      return this.imeKorisnika;
   }

   public void setImeKorisnika(java.lang.String imeKorisnika)
   {
      this.imeKorisnika = imeKorisnika;
   }

   public java.lang.String getPrezimeKorisnika()
   {
      return this.prezimeKorisnika;
   }

   public void setPrezimeKorisnika(java.lang.String prezimeKorisnika)
   {
      this.prezimeKorisnika = prezimeKorisnika;
   }

   public java.lang.String getAdresaKorisnika()
   {
      return this.adresaKorisnika;
   }

   public void setAdresaKorisnika(java.lang.String adresaKorisnika)
   {
      this.adresaKorisnika = adresaKorisnika;
   }

   public java.lang.String getBrojTelefonaKorisnika()
   {
      return this.brojTelefonaKorisnika;
   }

   public void setBrojTelefonaKorisnika(java.lang.String brojTelefonaKorisnika)
   {
      this.brojTelefonaKorisnika = brojTelefonaKorisnika;
   }

   public java.lang.String getOibKorisnika()
   {
      return this.oibKorisnika;
   }

   public void setOibKorisnika(java.lang.String oibKorisnika)
   {
      this.oibKorisnika = oibKorisnika;
   }

   public Korisnik(java.lang.Integer korisnikId,
         java.lang.String imeKorisnika, java.lang.String prezimeKorisnika,
         java.lang.String adresaKorisnika,
         java.lang.String brojTelefonaKorisnika,
         java.lang.String oibKorisnika)
   {
      this.korisnikId = korisnikId;
      this.imeKorisnika = imeKorisnika;
      this.prezimeKorisnika = prezimeKorisnika;
      this.adresaKorisnika = adresaKorisnika;
      this.brojTelefonaKorisnika = brojTelefonaKorisnika;
      this.oibKorisnika = oibKorisnika;
   }

}