package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NalogIzvedba implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Nalog_id")
   private java.lang.String nalogId;
   @org.kie.api.definition.type.Label(value = "Naziv_naloga")
   private java.lang.String nazivNaloga;
   @org.kie.api.definition.type.Label(value = "Datum_naloga")
   private java.util.Date datumNaloga;

   public NalogIzvedba()
   {
   }

   public java.lang.String getNalogId()
   {
      return this.nalogId;
   }

   public void setNalogId(java.lang.String nalogId)
   {
      this.nalogId = nalogId;
   }

   public java.lang.String getNazivNaloga()
   {
      return this.nazivNaloga;
   }

   public void setNazivNaloga(java.lang.String nazivNaloga)
   {
      this.nazivNaloga = nazivNaloga;
   }

   public java.util.Date getDatumNaloga()
   {
      return this.datumNaloga;
   }

   public void setDatumNaloga(java.util.Date datumNaloga)
   {
      this.datumNaloga = datumNaloga;
   }

   public NalogIzvedba(java.lang.String nalogId, java.lang.String nazivNaloga,
         java.util.Date datumNaloga)
   {
      this.nalogId = nalogId;
      this.nazivNaloga = nazivNaloga;
      this.datumNaloga = datumNaloga;
   }

}