package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NalogIzvedba implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("naloz izvedba id")
   private java.lang.Integer nalogIzvedbaId;
   @org.kie.api.definition.type.Label("datum naloga")
   private java.util.Date datumNaloga;
   @org.kie.api.definition.type.Label("nazivNaloga")
   private java.lang.String nazivNaloga;
   @org.kie.api.definition.type.Label("prikljucak")
   private bpm_vvg_2015.procesiugovaranjaprikljucaka.Prikljucak prikljucak;

   @org.kie.api.definition.type.Label(value = "Datum zaprimanja naloga")
   private java.util.Date datumZaprimanjaNaloga;

   public NalogIzvedba()
   {
   }

   public java.lang.Integer getNalogIzvedbaId()
   {
      return this.nalogIzvedbaId;
   }

   public void setNalogIzvedbaId(java.lang.Integer nalogIzvedbaId)
   {
      this.nalogIzvedbaId = nalogIzvedbaId;
   }

   public java.util.Date getDatumNaloga()
   {
      return this.datumNaloga;
   }

   public void setDatumNaloga(java.util.Date datumNaloga)
   {
      this.datumNaloga = datumNaloga;
   }

   public java.lang.String getNazivNaloga()
   {
      return this.nazivNaloga;
   }

   public void setNazivNaloga(java.lang.String nazivNaloga)
   {
      this.nazivNaloga = nazivNaloga;
   }

   public bpm_vvg_2015.procesiugovaranjaprikljucaka.Prikljucak getPrikljucak()
   {
      return this.prikljucak;
   }

   public void setPrikljucak(
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Prikljucak prikljucak)
   {
      this.prikljucak = prikljucak;
   }

   public java.util.Date getDatumZaprimanjaNaloga()
   {
      return this.datumZaprimanjaNaloga;
   }

   public void setDatumZaprimanjaNaloga(java.util.Date datumZaprimanjaNaloga)
   {
      this.datumZaprimanjaNaloga = datumZaprimanjaNaloga;
   }

   public NalogIzvedba(java.lang.Integer nalogIzvedbaId,
         java.util.Date datumNaloga, java.lang.String nazivNaloga,
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Prikljucak prikljucak,
         java.util.Date datumZaprimanjaNaloga)
   {
      this.nalogIzvedbaId = nalogIzvedbaId;
      this.datumNaloga = datumNaloga;
      this.nazivNaloga = nazivNaloga;
      this.prikljucak = prikljucak;
      this.datumZaprimanjaNaloga = datumZaprimanjaNaloga;
   }

}