package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Obavijest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "naziv obavijesti")
   private java.lang.String nazivObavijesti;
   @org.kie.api.definition.type.Label(value = "obavijest id")
   private java.lang.Integer obavijestId;
   @org.kie.api.definition.type.Label(value = "tekst obavijesti")
   private java.lang.String tekstObavijesti;
   @org.kie.api.definition.type.Label(value = "zahtjev")
   private bpm_vvg_2015.procesiugovaranjaprikljucaka.Zahtjev zahtjev;

   public Obavijest()
   {
   }

   public java.lang.String getNazivObavijesti()
   {
      return this.nazivObavijesti;
   }

   public void setNazivObavijesti(java.lang.String nazivObavijesti)
   {
      this.nazivObavijesti = nazivObavijesti;
   }

   public java.lang.Integer getObavijestId()
   {
      return this.obavijestId;
   }

   public void setObavijestId(java.lang.Integer obavijestId)
   {
      this.obavijestId = obavijestId;
   }

   public java.lang.String getTekstObavijesti()
   {
      return this.tekstObavijesti;
   }

   public void setTekstObavijesti(java.lang.String tekstObavijesti)
   {
      this.tekstObavijesti = tekstObavijesti;
   }

   public bpm_vvg_2015.procesiugovaranjaprikljucaka.Zahtjev getZahtjev()
   {
      return this.zahtjev;
   }

   public void setZahtjev(
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Zahtjev zahtjev)
   {
      this.zahtjev = zahtjev;
   }

   public Obavijest(java.lang.String nazivObavijesti,
         java.lang.Integer obavijestId, java.lang.String tekstObavijesti,
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Zahtjev zahtjev)
   {
      this.nazivObavijesti = nazivObavijesti;
      this.obavijestId = obavijestId;
      this.tekstObavijesti = tekstObavijesti;
      this.zahtjev = zahtjev;
   }

}