package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prikljucak implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Prikljucak_id")
   private java.lang.String prikljucakId;
   @org.kie.api.definition.type.Label(value = "Adresa_prikljucka")
   private java.lang.String adresaPrikljucka;
   @org.kie.api.definition.type.Label(value = "Broj_katastarske_cestice")
   private java.lang.String katastarskaCesticaBroj;
   @org.kie.api.definition.type.Label(value = "Katastarska_opcina")
   private java.lang.String katastarskaOpcina;
   @org.kie.api.definition.type.Label(value = "Vrsta_prikljucka")
   private java.lang.String vrstaPrikljucka;
   @org.kie.api.definition.type.Label(value = "Duzina_prikljucka")
   private java.lang.String duzinaPrikljucka;
   @org.kie.api.definition.type.Label(value = "Profil_prikljucka")
   private java.lang.String profilPrikljucka;
   @org.kie.api.definition.type.Label(value = "Dubina_prikljucka")
   private java.lang.String dubinaPrikljucka;
   @org.kie.api.definition.type.Label(value = "Cijena_prikljucka")
   private java.lang.String cijenaPrikljucka;

   public Prikljucak()
   {
   }

   public java.lang.String getPrikljucakId()
   {
      return this.prikljucakId;
   }

   public void setPrikljucakId(java.lang.String prikljucakId)
   {
      this.prikljucakId = prikljucakId;
   }

   public java.lang.String getAdresaPrikljucka()
   {
      return this.adresaPrikljucka;
   }

   public void setAdresaPrikljucka(java.lang.String adresaPrikljucka)
   {
      this.adresaPrikljucka = adresaPrikljucka;
   }

   public java.lang.String getKatastarskaCesticaBroj()
   {
      return this.katastarskaCesticaBroj;
   }

   public void setKatastarskaCesticaBroj(
         java.lang.String katastarskaCesticaBroj)
   {
      this.katastarskaCesticaBroj = katastarskaCesticaBroj;
   }

   public java.lang.String getKatastarskaOpcina()
   {
      return this.katastarskaOpcina;
   }

   public void setKatastarskaOpcina(java.lang.String katastarskaOpcina)
   {
      this.katastarskaOpcina = katastarskaOpcina;
   }

   public java.lang.String getVrstaPrikljucka()
   {
      return this.vrstaPrikljucka;
   }

   public void setVrstaPrikljucka(java.lang.String vrstaPrikljucka)
   {
      this.vrstaPrikljucka = vrstaPrikljucka;
   }

   public java.lang.String getDuzinaPrikljucka()
   {
      return this.duzinaPrikljucka;
   }

   public void setDuzinaPrikljucka(java.lang.String duzinaPrikljucka)
   {
      this.duzinaPrikljucka = duzinaPrikljucka;
   }

   public java.lang.String getProfilPrikljucka()
   {
      return this.profilPrikljucka;
   }

   public void setProfilPrikljucka(java.lang.String profilPrikljucka)
   {
      this.profilPrikljucka = profilPrikljucka;
   }

   public java.lang.String getDubinaPrikljucka()
   {
      return this.dubinaPrikljucka;
   }

   public void setDubinaPrikljucka(java.lang.String dubinaPrikljucka)
   {
      this.dubinaPrikljucka = dubinaPrikljucka;
   }

   public java.lang.String getCijenaPrikljucka()
   {
      return this.cijenaPrikljucka;
   }

   public void setCijenaPrikljucka(java.lang.String cijenaPrikljucka)
   {
      this.cijenaPrikljucka = cijenaPrikljucka;
   }

   public Prikljucak(java.lang.String prikljucakId,
         java.lang.String adresaPrikljucka,
         java.lang.String katastarskaCesticaBroj,
         java.lang.String katastarskaOpcina,
         java.lang.String vrstaPrikljucka,
         java.lang.String duzinaPrikljucka,
         java.lang.String profilPrikljucka,
         java.lang.String dubinaPrikljucka, java.lang.String cijenaPrikljucka)
   {
      this.prikljucakId = prikljucakId;
      this.adresaPrikljucka = adresaPrikljucka;
      this.katastarskaCesticaBroj = katastarskaCesticaBroj;
      this.katastarskaOpcina = katastarskaOpcina;
      this.vrstaPrikljucka = vrstaPrikljucka;
      this.duzinaPrikljucka = duzinaPrikljucka;
      this.profilPrikljucka = profilPrikljucka;
      this.dubinaPrikljucka = dubinaPrikljucka;
      this.cijenaPrikljucka = cijenaPrikljucka;
   }

}