package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prikljucak implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Adresa Prikljucka")
   private java.lang.String adresaPrikljucka;
   @org.kie.api.definition.type.Label(value = "izmjera prikljucka")
   private bpm_vvg_2015.procesiugovaranjaprikljucaka.IzmjeraPrikljucka izmjeraPrikljucka;
   @org.kie.api.definition.type.Label(value = "katastarska cestica broj")
   private java.lang.String katastarskaCesticaBroj;
   @org.kie.api.definition.type.Label(value = "katastarskaOpcina")
   private java.lang.String katstarskaOpcina;
   @org.kie.api.definition.type.Label(value = "okno")
   private java.lang.Boolean oknoPrikljucka;
   @org.kie.api.definition.type.Label(value = "prikljucak id")
   private java.lang.Integer prikljucakId;
   @org.kie.api.definition.type.Label(value = "vrsta prikljucka")
   private java.lang.String vrstaPrikljucka;

   public Prikljucak()
   {
   }

   public java.lang.String getAdresaPrikljucka()
   {
      return this.adresaPrikljucka;
   }

   public void setAdresaPrikljucka(java.lang.String adresaPrikljucka)
   {
      this.adresaPrikljucka = adresaPrikljucka;
   }

   public bpm_vvg_2015.procesiugovaranjaprikljucaka.IzmjeraPrikljucka getIzmjeraPrikljucka()
   {
      return this.izmjeraPrikljucka;
   }

   public void setIzmjeraPrikljucka(
         bpm_vvg_2015.procesiugovaranjaprikljucaka.IzmjeraPrikljucka izmjeraPrikljucka)
   {
      this.izmjeraPrikljucka = izmjeraPrikljucka;
   }

   public java.lang.String getKatastarskaCesticaBroj()
   {
      return this.katastarskaCesticaBroj;
   }

   public void setKatastarskaCesticaBroj(
         java.lang.String katastarskaCesticaBroj)
   {
      this.katastarskaCesticaBroj = katastarskaCesticaBroj;
   }

   public java.lang.String getKatstarskaOpcina()
   {
      return this.katstarskaOpcina;
   }

   public void setKatstarskaOpcina(java.lang.String katstarskaOpcina)
   {
      this.katstarskaOpcina = katstarskaOpcina;
   }

   public java.lang.Boolean getOknoPrikljucka()
   {
      return this.oknoPrikljucka;
   }

   public void setOknoPrikljucka(java.lang.Boolean oknoPrikljucka)
   {
      this.oknoPrikljucka = oknoPrikljucka;
   }

   public java.lang.Integer getPrikljucakId()
   {
      return this.prikljucakId;
   }

   public void setPrikljucakId(java.lang.Integer prikljucakId)
   {
      this.prikljucakId = prikljucakId;
   }

   public java.lang.String getVrstaPrikljucka()
   {
      return this.vrstaPrikljucka;
   }

   public void setVrstaPrikljucka(java.lang.String vrstaPrikljucka)
   {
      this.vrstaPrikljucka = vrstaPrikljucka;
   }

   public Prikljucak(
         java.lang.String adresaPrikljucka,
         bpm_vvg_2015.procesiugovaranjaprikljucaka.IzmjeraPrikljucka izmjeraPrikljucka,
         java.lang.String katastarskaCesticaBroj,
         java.lang.String katstarskaOpcina,
         java.lang.Boolean oknoPrikljucka, java.lang.Integer prikljucakId,
         java.lang.String vrstaPrikljucka)
   {
      this.adresaPrikljucka = adresaPrikljucka;
      this.izmjeraPrikljucka = izmjeraPrikljucka;
      this.katastarskaCesticaBroj = katastarskaCesticaBroj;
      this.katstarskaOpcina = katstarskaOpcina;
      this.oknoPrikljucka = oknoPrikljucka;
      this.prikljucakId = prikljucakId;
      this.vrstaPrikljucka = vrstaPrikljucka;
   }

}