package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Racun implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "racun id")
   private java.lang.Integer racunId;
   @org.kie.api.definition.type.Label(value = "naziv racuna")
   private java.lang.String nazivRacuna;
   @org.kie.api.definition.type.Label(value = "datum izdavanja racuna")
   private java.util.Date datumIzdavanjaRacuna;

   public Racun()
   {
   }

   public java.lang.Integer getRacunId()
   {
      return this.racunId;
   }

   public void setRacunId(java.lang.Integer racunId)
   {
      this.racunId = racunId;
   }

   public java.lang.String getNazivRacuna()
   {
      return this.nazivRacuna;
   }

   public void setNazivRacuna(java.lang.String nazivRacuna)
   {
      this.nazivRacuna = nazivRacuna;
   }

   public java.util.Date getDatumIzdavanjaRacuna()
   {
      return this.datumIzdavanjaRacuna;
   }

   public void setDatumIzdavanjaRacuna(java.util.Date datumIzdavanjaRacuna)
   {
      this.datumIzdavanjaRacuna = datumIzdavanjaRacuna;
   }

   public Racun(java.lang.Integer racunId, java.lang.String nazivRacuna,
         java.util.Date datumIzdavanjaRacuna)
   {
      this.racunId = racunId;
      this.nazivRacuna = nazivRacuna;
      this.datumIzdavanjaRacuna = datumIzdavanjaRacuna;
   }

}