package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Racun implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Racun_id")
   private java.lang.String racunaId;
   @org.kie.api.definition.type.Label("IznosRacuna")
   private java.lang.String iznosRacuna;
   @org.kie.api.definition.type.Label("Datum_uplate")
   private java.util.Date datumUplate;
   @org.kie.api.definition.type.Label("Iznos_uplate")
   private String iznosUplate;

   public Racun()
   {
   }

   public java.lang.String getRacunaId()
   {
      return this.racunaId;
   }

   public void setRacunaId(java.lang.String racunaId)
   {
      this.racunaId = racunaId;
   }

   public java.lang.String getIznosRacuna()
   {
      return this.iznosRacuna;
   }

   public void setIznosRacuna(java.lang.String iznosRacuna)
   {
      this.iznosRacuna = iznosRacuna;
   }

   public java.util.Date getDatumUplate()
   {
      return this.datumUplate;
   }

   public void setDatumUplate(java.util.Date datumUplate)
   {
      this.datumUplate = datumUplate;
   }

   public java.lang.String getIznosUplate()
   {
      return this.iznosUplate;
   }

   public void setIznosUplate(java.lang.String iznosUplate)
   {
      this.iznosUplate = iznosUplate;
   }

   public Racun(java.lang.String racunaId, java.lang.String iznosRacuna,
         java.util.Date datumUplate, java.lang.String iznosUplate)
   {
      this.racunaId = racunaId;
      this.iznosRacuna = iznosRacuna;
      this.datumUplate = datumUplate;
      this.iznosUplate = iznosUplate;
   }

}