package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StatusZahtjeva implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "status zahtjeva id")
   private java.lang.Integer statusZahtjevaId;
   @org.kie.api.definition.type.Label(value = "naziv statusa zahtjeva")
   private java.lang.String nazivStatusaZahtjeva;

   public StatusZahtjeva()
   {
   }

   public java.lang.Integer getStatusZahtjevaId()
   {
      return this.statusZahtjevaId;
   }

   public void setStatusZahtjevaId(java.lang.Integer statusZahtjevaId)
   {
      this.statusZahtjevaId = statusZahtjevaId;
   }

   public java.lang.String getNazivStatusaZahtjeva()
   {
      return this.nazivStatusaZahtjeva;
   }

   public void setNazivStatusaZahtjeva(java.lang.String nazivStatusaZahtjeva)
   {
      this.nazivStatusaZahtjeva = nazivStatusaZahtjeva;
   }

   public StatusZahtjeva(java.lang.Integer statusZahtjevaId,
         java.lang.String nazivStatusaZahtjeva)
   {
      this.statusZahtjevaId = statusZahtjevaId;
      this.nazivStatusaZahtjeva = nazivStatusaZahtjeva;
   }

}