package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Troskovnik implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "artikl")
   private bpm_vvg_2015.procesiugovaranjaprikljucaka.Artikl artikl;
   @org.kie.api.definition.type.Label(value = "cijena prikljucka")
   private java.lang.String cijenaPrikljucka;
   @org.kie.api.definition.type.Label(value = "kolicinaArtikla")
   private java.lang.String kolicinaArtikla;
   @org.kie.api.definition.type.Label(value = "troskovnik id")
   private java.lang.String troskovnikId;

   public Troskovnik()
   {
   }

   public bpm_vvg_2015.procesiugovaranjaprikljucaka.Artikl getArtikl()
   {
      return this.artikl;
   }

   public void setArtikl(
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Artikl artikl)
   {
      this.artikl = artikl;
   }

   public java.lang.String getCijenaPrikljucka()
   {
      return this.cijenaPrikljucka;
   }

   public void setCijenaPrikljucka(java.lang.String cijenaPrikljucka)
   {
      this.cijenaPrikljucka = cijenaPrikljucka;
   }

   public java.lang.String getKolicinaArtikla()
   {
      return this.kolicinaArtikla;
   }

   public void setKolicinaArtikla(java.lang.String kolicinaArtikla)
   {
      this.kolicinaArtikla = kolicinaArtikla;
   }

   public java.lang.String getTroskovnikId()
   {
      return this.troskovnikId;
   }

   public void setTroskovnikId(java.lang.String troskovnikId)
   {
      this.troskovnikId = troskovnikId;
   }

   public Troskovnik(bpm_vvg_2015.procesiugovaranjaprikljucaka.Artikl artikl,
         java.lang.String cijenaPrikljucka,
         java.lang.String kolicinaArtikla, java.lang.String troskovnikId)
   {
      this.artikl = artikl;
      this.cijenaPrikljucka = cijenaPrikljucka;
      this.kolicinaArtikla = kolicinaArtikla;
      this.troskovnikId = troskovnikId;
   }

}