package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ugovor implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Ugovor_id")
   private java.lang.String ugovorId;
   @org.kie.api.definition.type.Label(value = "Naziv_ugovora")
   private java.lang.String nazivUgovora;
   @org.kie.api.definition.type.Label(value = "Datum_ugovora")
   private java.util.Date datumUgovora;
   @org.kie.api.definition.type.Label(value = "Datum_potpisa")
   private java.util.Date datumPotpisa;

   public Ugovor()
   {
   }

   public java.lang.String getUgovorId()
   {
      return this.ugovorId;
   }

   public void setUgovorId(java.lang.String ugovorId)
   {
      this.ugovorId = ugovorId;
   }

   public java.lang.String getNazivUgovora()
   {
      return this.nazivUgovora;
   }

   public void setNazivUgovora(java.lang.String nazivUgovora)
   {
      this.nazivUgovora = nazivUgovora;
   }

   public java.util.Date getDatumUgovora()
   {
      return this.datumUgovora;
   }

   public void setDatumUgovora(java.util.Date datumUgovora)
   {
      this.datumUgovora = datumUgovora;
   }

   public java.util.Date getDatumPotpisa()
   {
      return this.datumPotpisa;
   }

   public void setDatumPotpisa(java.util.Date datumPotpisa)
   {
      this.datumPotpisa = datumPotpisa;
   }

   public Ugovor(java.lang.String ugovorId, java.lang.String nazivUgovora,
         java.util.Date datumUgovora, java.util.Date datumPotpisa)
   {
      this.ugovorId = ugovorId;
      this.nazivUgovora = nazivUgovora;
      this.datumUgovora = datumUgovora;
      this.datumPotpisa = datumPotpisa;
   }

}