package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ugovor implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ugovor id")
   private java.lang.Integer ugovorId;
   @org.kie.api.definition.type.Label(value = "naziv ugovora")
   private java.lang.String nazivUgovora;
   @org.kie.api.definition.type.Label(value = "datum izrade ugovora")
   private java.util.Date datumIzradeUgovora;
   @org.kie.api.definition.type.Label(value = "zahtjev")
   private bpm_vvg_2015.procesiugovaranjaprikljucaka.Zahtjev zahtjev;
   @org.kie.api.definition.type.Label(value = "placanje po ugovoru")
   private bpm_vvg_2015.procesiugovaranjaprikljucaka.Placanje placanjePoUgovoru;
   @org.kie.api.definition.type.Label(value = "racun")
   private bpm_vvg_2015.procesiugovaranjaprikljucaka.Racun racun;

   public Ugovor()
   {
   }

   public java.lang.Integer getUgovorId()
   {
      return this.ugovorId;
   }

   public void setUgovorId(java.lang.Integer ugovorId)
   {
      this.ugovorId = ugovorId;
   }

   public java.lang.String getNazivUgovora()
   {
      return this.nazivUgovora;
   }

   public void setNazivUgovora(java.lang.String nazivUgovora)
   {
      this.nazivUgovora = nazivUgovora;
   }

   public java.util.Date getDatumIzradeUgovora()
   {
      return this.datumIzradeUgovora;
   }

   public void setDatumIzradeUgovora(java.util.Date datumIzradeUgovora)
   {
      this.datumIzradeUgovora = datumIzradeUgovora;
   }

   public bpm_vvg_2015.procesiugovaranjaprikljucaka.Zahtjev getZahtjev()
   {
      return this.zahtjev;
   }

   public void setZahtjev(
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Zahtjev zahtjev)
   {
      this.zahtjev = zahtjev;
   }

   public bpm_vvg_2015.procesiugovaranjaprikljucaka.Placanje getPlacanjePoUgovoru()
   {
      return this.placanjePoUgovoru;
   }

   public void setPlacanjePoUgovoru(
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Placanje placanjePoUgovoru)
   {
      this.placanjePoUgovoru = placanjePoUgovoru;
   }

   public bpm_vvg_2015.procesiugovaranjaprikljucaka.Racun getRacun()
   {
      return this.racun;
   }

   public void setRacun(bpm_vvg_2015.procesiugovaranjaprikljucaka.Racun racun)
   {
      this.racun = racun;
   }

   public Ugovor(
         java.lang.Integer ugovorId,
         java.lang.String nazivUgovora,
         java.util.Date datumIzradeUgovora,
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Zahtjev zahtjev,
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Placanje placanjePoUgovoru,
         bpm_vvg_2015.procesiugovaranjaprikljucaka.Racun racun)
   {
      this.ugovorId = ugovorId;
      this.nazivUgovora = nazivUgovora;
      this.datumIzradeUgovora = datumIzradeUgovora;
      this.zahtjev = zahtjev;
      this.placanjePoUgovoru = placanjePoUgovoru;
      this.racun = racun;
   }

}