package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vodomjer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Broj vodomjera")
   private java.lang.String vodomjerId;
   @org.kie.api.definition.type.Label(value = "Profil vodomjera")
   private java.lang.String profilVodomjera;

   public Vodomjer()
   {
   }

   public java.lang.String getVodomjerId()
   {
      return this.vodomjerId;
   }

   public void setVodomjerId(java.lang.String vodomjerId)
   {
      this.vodomjerId = vodomjerId;
   }

   public java.lang.String getProfilVodomjera()
   {
      return this.profilVodomjera;
   }

   public void setProfilVodomjera(java.lang.String profilVodomjera)
   {
      this.profilVodomjera = profilVodomjera;
   }

   public Vodomjer(java.lang.String vodomjerId,
         java.lang.String profilVodomjera)
   {
      this.vodomjerId = vodomjerId;
      this.profilVodomjera = profilVodomjera;
   }

}