package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZahtjevDozvola implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "zadtjev dozvola")
   private java.lang.Integer zahtjevDozvolaId;
   @org.kie.api.definition.type.Label(value = "naziv zahtjeva")
   private java.lang.String nazivZahtjeva;
   @org.kie.api.definition.type.Label(value = "datum izrade")
   private java.util.Date datumIzrade;

   public ZahtjevDozvola()
   {
   }

   public java.lang.Integer getZahtjevDozvolaId()
   {
      return this.zahtjevDozvolaId;
   }

   public void setZahtjevDozvolaId(java.lang.Integer zahtjevDozvolaId)
   {
      this.zahtjevDozvolaId = zahtjevDozvolaId;
   }

   public java.lang.String getNazivZahtjeva()
   {
      return this.nazivZahtjeva;
   }

   public void setNazivZahtjeva(java.lang.String nazivZahtjeva)
   {
      this.nazivZahtjeva = nazivZahtjeva;
   }

   public java.util.Date getDatumIzrade()
   {
      return this.datumIzrade;
   }

   public void setDatumIzrade(java.util.Date datumIzrade)
   {
      this.datumIzrade = datumIzrade;
   }

   public ZahtjevDozvola(java.lang.Integer zahtjevDozvolaId,
         java.lang.String nazivZahtjeva, java.util.Date datumIzrade)
   {
      this.zahtjevDozvolaId = zahtjevDozvolaId;
      this.nazivZahtjeva = nazivZahtjeva;
      this.datumIzrade = datumIzrade;
   }

}