package bpm_vvg_2015.procesiugovaranjaprikljucaka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Zahtjev implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Zahtjev_id")
   private java.lang.String zahtjevId;
   @org.kie.api.definition.type.Label("Datum_zahtjeva")
   private java.util.Date datumZahtjeva;

   private java.util.Date datumPonistenja;

   public Zahtjev()
   {
   }

   public java.lang.String getZahtjevId()
   {
      return this.zahtjevId;
   }

   public void setZahtjevId(java.lang.String zahtjevId)
   {
      this.zahtjevId = zahtjevId;
   }

   public java.util.Date getDatumZahtjeva()
   {
      return this.datumZahtjeva;
   }

   public void setDatumZahtjeva(java.util.Date datumZahtjeva)
   {
      this.datumZahtjeva = datumZahtjeva;
   }

   public java.util.Date getDatumPonistenja()
   {
      return this.datumPonistenja;
   }

   public void setDatumPonistenja(java.util.Date datumPonistenja)
   {
      this.datumPonistenja = datumPonistenja;
   }

   public Zahtjev(java.lang.String zahtjevId, java.util.Date datumZahtjeva,
         java.util.Date datumPonistenja)
   {
      this.zahtjevId = zahtjevId;
      this.datumZahtjeva = datumZahtjeva;
      this.datumPonistenja = datumPonistenja;
   }

}